# Generated by Django 3.2.18 on 2023-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_alter_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
