# Generated by Django 3.2.18 on 2023-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0003_alter_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
