# Generated by Django 3.2.18 on 2023-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0004_alter_student_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
